### ISSUE TITLE
Jigsaw compatibility

### ISSUE THREAD

**Issue by rahmanusta** [aalmiray/ikonli#8]
I don't know whether is it a JDK 9 bug, but I get the following error while using ikonli.

```
java.lang.NoClassDefFoundError: Could not initialize class org.kordamp.ikonli.javafx.FontIcon$StyleableProperties
        at org.kordamp.ikonli.javafx.FontIcon.getClassCssMetaData(FontIcon.java:301)
        at org.kordamp.ikonli.javafx.FontIcon.getCssMetaData(FontIcon.java:305)
        at javafx.graphics/javafx.scene.CssStyleHelper$CacheContainer.<init>(CssStyleHelper.java:380)
```

Do you have any opinion for that?

Thanks.

**Comment by rahmanusta** [comment]
The reason is converter classes in com.sun.** moved to javafx.css.converter, but still I couldn't build project with jdk 9. I used the following JVM paremeters:

`-Dsun.reflect.debugModuleAccessChecks=true --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/sun.security.provider=ALL-UNNAMED`

**Comment by rahmanusta** [comment]
Have you ever try to build ikonli with Java 9 Jigsaw @aalmiray ? Thanks.

**Comment by aalmiray** [comment]
hint: consider using MJARs instead of multiple JARs with classifiers. See [JEP 238](http://openjdk.java.net/jeps/238).

Must figure out a way to build MJARs with Gradle.

**Comment by aalmiray** [comment]
This has turn out to be a major issue. `FontIcon` makes use of private APIs in Java8 that have been migrated to public in Java9. In order to maintain compatibility 2 versions of this class must be compiled, one with JDK8 and the other with JDK9. This means the build must have access to both JDKs and build each sourceset separately, then combine resources in a single MRJARs. Gradle can't do this and neither can Maven. Resorting to Makefiles or shell scripts is the only way, and that's too low level and troublesome.

Alternatives are if a single JAR is desired:
 - keep Ikonli compatible with Java8 until it's phased out.
 - upgrade all of Ikonli to Java9. Can't use Ikonli on Java8.

**Comment by aalmiray** [comment]
Ikonli 2.0.0 has been released. It works on JDK9 and automatic modules.

**Comment by rahmanusta** [comment]
Thank you Andres!

27 Eyl 2017 16:46 tarihinde "Andres Almiray" <notifications@github.com>
yazdı:
